#!/bin/bash
#
kell=`date | cut -c12-13`
#
if [ $kell -gt 6 -a $kell -lt 12 ]; 
then tervitus="tere hommikust, "
elif [ $kell -ge 12 -a $kell -lt 16 ];
then tervitus="tere päevast, "
elif [ $kell -ge 16 -a $kell -lt 20 ];
then tervitus="tere ohtust, "
else tervitus="KAO MAGAMA, "
fi
echo -n "$tervitus "
echo -n `who am i | cut -fl -d"." | cut -c1 |tr [:lower] [:upper:]`
echo -n `who am i | cut -fl -d"." | cut -c2-`
echo "!"
#
