#!/bin/bash
#

osch=0
echo "1. Unix (Sun Os)"
echo "2. Linux (Red Hat)"

echo -n "Select our os choise [1 or 2]? "
read osch

if [ $osch -eq 1] ; then
	echo "You Pick up Unix (Sun Os)"
else #### nested if i.e if witgin if ######
	if [ $osch -eq 2 ] ; then
		echo "You Pick uo Linux (Red Hat)"
	else
		echo "What you dont't like Unix/Linux OS???"
	fi
fi
#
