#!/bin/bash
#
#
echo -n "Palun, sisesta auto nimi: "
read rental

case $rental in
	"car") echo "For $rental Rs.20 per k/m";;
	"van") echo "For $rental Rs.10 per k/m";;
	"jeep") echo "For $rental Rs.5 per k/m";;
	"bicycle") echo "For $rental 20 paisa per k/m";;
	*) echo "Vabandust, meil ei ole Sulle $rental";;
esac
