#!/bin/bash
#
echo -n "Sisesta kuu number: "
read number

case $number in
	"1") echo "See kuu on jaanuar ja siis on talv";;
	"2") echo "See kuu on veebruar ja siis on talv";;
	"3") echo "See kuu on märts ja siis on kevad";;
	"4") echo "See kuu on aprill ja siis on kevad";;
	"5") echo "See kuu on mai ja siis on kevad";;
	"6") echo "See kuu on juuni ja siis on suvi";;
	"7") echo "See kuu on juuli ja siis on suvi";;
	"8") echo "See kuu on august ja siis on suvi";;
	"9") echo "See kuu on september ja siis on sügis";;
	"10") echo "See kuu on oktoober ja siis on sügis";;
	"11") echo "See kuu on november ja siis on sügis";;
	"12") echo "See kuu on detsember ja siis on talv";;
	*) echo "Sisesta õige kuu (1-12)";;

esac
#


