#!/bin/bash
#
# kui sisestad ridade arvu ning real olevad sümbolid
echo -n "Sisesta ridade arv: "
read r
echo -n "Sisesta tärnide arv reas: "
read t
for (( i = 1; i <= $r; i++ )) #pikkus
do
echo -n "$i"
if [ "$i" == 1 ] || [ "$i" == $r ]
then
for (( j = 1; j <= $t; j++ )) #laius
do
echo -n "*" #need millest see koosneb
done
else
echo -n "*"
for (( a = 2; a < $t; a++ ))
do
echo -n " "
done
echo -n "*"
fi
echo ""
done
#
